sudo: required
services: 
  - docker

before_install:
  - docker build -t pedrobrunorl/docker-react -f Dockerfile.dev .

script:
  - docker run pedrobrunorl/docker-react npm run test -- --coverage   
